workspace = { members = ["rust_webgl_renderer"] }
[package]
name = "barren_plateau"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
actix-rt = "2.9.0"
actix-files = "0.6.5"
